### PR TITLE
Fix Slow performance issue if changing many dragons on Mobile browser

### PR DESCRIPTION
**Pull request by nganlamsong**
When I used this website on my mobile phone browser, after changing to view many dragons or auras, the browser starts to lag and is slowed down dramatically. This is just an attempt to fix this issue because I think Spine Canvases used in this website are not disposed correctly, dumping the memory of browser, causing lag and unresponsiveness.

PS: a DVC player from across the sea, also a Web Developer.

### CODE REVIEW

**Comment by vega-spica** [comment]
hey, just letting you know i've tested this, and it unfortunately didn't have any change in performance when changing auras. i replied to your post about it on discord in more detail, as i'm more active there.

**Comment by nganlamsong** [comment]
Thanks, I'm creating a repo to test it myself because easier to test it as a normal website.

**Comment by nganlamsong** [comment]
I did publish a copy of your repo and test the website myself on my Mobile phone, I have changed the dragons and personalities for a few dozen of times and the web browser still handle it without unresponsiveness. Before that, even changing 10 times would break my browser.

**Comment by vega-spica** [comment]
ah, i didn't test it on mobile, only on my PC.
i can try and merge this if you'd like to test it here as well -- i'll do the same.

**Pull request merged**
